---
- name: Playbook to install for yocto project on Ubuntu linux machine.
  hosts: all
  tasks:
    # Install essential packages for Ubuntu yocto
    - name: Install essential packages for for yocto project on Ubuntu.
      apt:
        pkg:
          - gawk
          - wget
          - git-core
          - diffstat
          - unzip
          - texinfo
          - gcc-multilib
          - build-essential
          - chrpath
          - socat
          - cpio
          - python3
          - python3-pip
          - python3-pexpect
          - xz-utils
          - debianutils
          - iputils-ping
          - python3-git
          - python3-jinja2
          - libegl1-mesa
          - libsdl1.2-dev
          - pylint3
          - xterm
        state: present
        update_cache: true

    # Git checkout
    - name: Git checkout.
      git:
        repo: "git://git.yoctoproject.org/poky"
        dest: "/home/vagrant/poky"
        version: tags/yocto-3.1.3
      become: false

    # You can use shell to run other executables to perform actions inline
    - name: Run a series of commands to source an env and build it.
      shell: |
        cd /home/vagrant/poky
        source oe-init-build-env
        bitbake core-image-sato
      args:
        executable: /usr/bin/bash
      become: false
      register: oe_result

    - name: Display oe_result.
      debug:
        var: oe_result.stdout
      become: false
