---
- name: Playbook to install essential packages for yocto project on Ubuntu linux machine.
  hosts: all
  tasks:

    # Install build-essential package for Ubuntu
    - name: Install build-essential package for Ubuntu.
      apt:
        pkg:
          - build-essential
        state: present
        update_cache: true
      register: apt_pkg_result

    - name: Display apt_pkg_result.
      debug:
        var: apt_pkg_result.stdout
