# Fail if the vagrant-disksize plugin is not installed
unless Vagrant.has_plugin?("vagrant-disksize")
    raise 'vagrant-disksize is not installed!'
end

Vagrant.configure("2") do |config|

#    config.vm.hostname = "DISKEXTEND"
    config.vm.box = "bento/ubuntu-18.04"

    config.vm.provider "virtualbox" do |vb|
#      vb.name = "DISKEXTEND"
      vb.memory = "2048"
      vb.cpus = "2"
    end

#    config.vm.define :"DISKEXTEND" do |t|
#    end


    # Increase the default disk size of the bento image (64GB) to 96GB
    config.disksize.size = "96GB"

    # Run a script on provisioning the box to format the file system
    config.vm.provision "shell", path: "disk-extend.sh"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "main.yml"
        ansible.become = true
    end
    
end