# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-18.04"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end

    # Run a script on provisioning the box to format the file system
    # Only work on Ubuntu 18.04, Ubuntu 20.04 does not work
    # 
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "main.yml"
#      ansible.playbook = "main-build.yml"
      ansible.become = true
    end
    
end
