---
- name: Playbook to install for yocto project on Ubuntu linux machine.
  hosts: all
  tasks:

    # Install essential packages for Ubuntu yocto
    - name: Install essential packages for Ubuntu yocto.
      apt:
        pkg:
          - gawk
          - wget
          - git-core
          - diffstat
          - unzip
          - texinfo
          - gcc-multilib
          - build-essential
          - chrpath
          - socat
          - cpio
          - python3
          - python3-pip
          - python3-pexpect
          - xz-utils
          - debianutils
          - iputils-ping
          - python3-git
          - python3-jinja2
          - libegl1-mesa
          - libsdl1.2-dev
          - pylint3
          - xterm
        state: present
        update_cache: true
      register: apt_pkg_result

    - name: Display apt_pkg_result.
      debug:
        var: apt_pkg_result.stdout

    # Git checkout
    - name: Git checkout
      git:
        repo: "git://git.yoctoproject.org/poky"
        dest: "/home/vagrant/poky"
        version: tags/yocto-3.1.3
      become: false

    # Initialize the Build Environment
    - name: Source the bash_profile file
      shell: source /home/vagrant/poky/oe-init-build-env

    # Start the Build
    - name: Start the Build
      shell: /home/vagrant/poky/build/bitbake core-image-sato
