- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/Einsteinish/flask-vagrant-ansible
      repository_path: /home/vagrant/flask-vagrant-ansible

  tasks:
    - name: Install packages
      apt:
        name:
          - git
          - python-pip
          - nginx
        state: present
      
    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'


    - name: Copy Upstart configuration
      template: src=hello-world.upstart.j2 dest=/etc/init/hello-world.conf

    - name: Make sure our server is running
      service: name=hello-world state=started

    - name: Copy Nginx site
      template: src=hello-world.nginx.j2 dest=/etc/nginx/sites-enabled/hello-world
      notify:
        - restart nginx

    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

