IMAGE_NAME = "bento/ubuntu-20.04"

NODES_NUM = 3
NODES_CPU = 1
NODES_MEM = 512

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..NODES_NUM).each do |j|
        config.vm.define "ex61-n-#{j}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.provider "virtualbox" do |v|
                v.memory = NODES_MEM
                v.cpus = NODES_CPU
            end    
            
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "main.yml"                   
                #Redefine defaults
                ansible.extra_vars = {
                    k8s_node_admin_user:  "vagrant",
                    k8s_node_admin_group: "vagrant",
                }
            end

        end
    end
end
