---
- name: Playbook to install essential packages for yocto project on Ubuntu linux machine.
  hosts: all
  tasks:

    # Install essential packages for Ubuntu yocto
    - name: Install essential packages for for yocto project on Ubuntu.
      apt:
        pkg:
          - build-essential
        state: present
        update_cache: true
      register: apt_pkg_result

    - name: Display apt_pkg_result.
      debug:
        var: apt_pkg_result.stdout
